# TensorFlow

- TensorFlow je open source framework vzvinuty vyskumnikmi Goolge
- TensorFlow spracovava subory udajov, ktore su usporiadane ako vypoctove uzly vo forme grafu
- TensorFlow pouzivaju architekturutoku udajov, ktora pracuje so yovseobecnenymi medzivysledkami vypoctov

### import TensorFlow

In [8]:
import tensorflow as tf

### Tenzor

In [9]:
x = tf.constant (([1,2,3],
                 [4,5,6]))

In [10]:
print (x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### Shape - informuje o velkosti tenzora po kazdej z jeho osi

In [11]:
print (x.shape)

(2, 3)


### Dtype - informuje o type vsetkych prvkov v tenzore

In [12]:
print (x.dtype)

<dtype: 'int32'>


# Matematicke operacie

### Scitanie

In [13]:
(x+x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

### Nasobenie

In [14]:
(5*x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30]], dtype=int32)>

-